version: '3.8'

services:
    
    # Application
    app:
        build:
            context: .
            dockerfile: app.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "database"
        networks:
            - laravel
    # Web Server
    web:
        build:
            context: .
            dockerfile: web.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "app"
        ports:
            - 80:80
        networks:
            - laravel    
    # Database
    database:
        image: mysql:5.7
        volumes:
            - ./dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        # env_file:
        #     - .env
        ports:
            - 3307:3306
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

# volumes:
#     dbdata:
#         driver: local
